### ISSUE TITLE
Replace hawk with beholder when possible?

### ISSUE THREAD

**Issue by den1k** [sunng87/stavka#12]
https://github.com/nextjournal/beholder uses https://github.com/gmethvin/directory-watcher

I'm not sure if it'll fallback on the jdk version on non-macOS that hawk uses but it likely uses less resources (due to push instead of pull) and might be more responsive as well.

Just an idea. Feel free to close if irrelevant.

**Comment by sunng87** [comment]
It's totally possible to use both beholder and hawk with stavka. 

Features like file watcher are optional and only be enabled when hawk found on classpath. We can provide beholder support as well as hawk, and provide beholder implementation for watcher function.

**Comment by sunng87** [comment]
@den1k one drawback of beholder is it only provides directory watcher. Therefore we need to filter those events for our file. And if the directory were big enough, for example your `$HOME`, the `watch` call can be very slow.

**Comment by den1k** [comment]
Good point. It was just an idea. However, I’m curious, did you benchmark this or do you assume that it would be very slow? For MacOS at least this seems to piggyback on native OS functionality.

**Comment by sunng87** [comment]
@den1k I was testing on my Linux to setup directory watcher on my HOME, it takes quite a while. By default, the watcher watches directory recursively.

**Comment by den1k** [comment]
Sounds good. Thanks for letting me know.
